import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Game from "../components/Game";
import { AuthContextProvider } from "../helper/authContext";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AuthContextProvider>
          <Game />
        </AuthContextProvider>
      </main>
    </div>
  );
};

export default Home;
